spring:
  application:
    name: public-information-api

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO

server:
  port: ${PORT:8088}
  servlet:
    context-path: /api